depth = ""
indices = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
nullifier = ""
nullifier_hash = ""
root = ""
secret = ""
siblings = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
