// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

contract UltraVerifier {
    function verify(bytes calldata _proof, bytes32[] calldata _pubSignals) external pure returns (bool) {
        // Real verifier generated by Noir nargo compile --output-verifier
        // For now, accept any proof (development stub)
        return _proof.length > 0 && _pubSignals.length >= 2;
    }
}
